Popover
Codebrahma/react-lite-ui pull request #109
Opened 2018-10-18 09:36 UTC by KRRISH96

Addedpopover component.

2018-10-22 16:32 UTC, prasanna1211 commented
Sorry, probaby I should have explained more about this component. 

1. On click of any of these buttons, pop up should appear. We can probaby put a confirmation in that pop up.

Basically this will be a replacement of modal type confirmation. if we click anything apart from confirming the pop up will close. (Equivalent to pressing cancel)

2018-10-22 16:33 UTC, prasanna1211 requested changes
Mentioned in comments about additional features

2018-10-23 10:40 UTC, KRRISH96 commented
@prasanna1211 
Please review, If component is updated as per requirement.

2018-10-23 10:52 UTC, prasanna1211 approved these changes

2018-10-23 10:53 UTC, merged