fix(autocomplete): update autocomplete design
Codebrahma/react-lite-ui pull request #288
Opened 2018-12-28 11:07 UTC by rishichawda

#287

### Status :
In Development
##

### Description :

Update autocomplete component design.

##

### Related Issues :

#287 

## Todos
- [ ] Tests
- [ ] Documentation

2018-12-31 06:56 UTC, kaushiknishchay requested changes
[
<img width="343" alt="screenshot 2018-12-31 at 12 25 56 pm" src="https://user-images.githubusercontent.com/15786884/50555794-41171d00-0cf7-11e9-979f-b6492927b491.png">
](url)


The following style needs to be fixed, Everything else is good.

2018-12-31 07:16 UTC, rishichawda commented
@kaushiknishchay Updated the no results message.

2018-12-31 07:41 UTC, kaushiknishchay approved these changes

2019-01-01 06:27 UTC, KRRISH96 approved these changes

2019-01-01 12:53 UTC, merged

2019-01-03 08:18 UTC, rishichawda commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-lite-ui)
- [GitHub release](https://github.com/Codebrahma/react-lite-ui/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: