Card design update
Codebrahma/react-lite-ui pull request #290
Opened 2018-12-28 12:32 UTC by rishichawda

### Status :
Ready

### Description :

Update card component's design

##

### Related Issues :

#287 

## Todos
- [ ] Tests
- [ ] Documentation

2018-12-31 07:33 UTC, kaushiknishchay requested changes

2018-12-31 07:33 UTC, kaushiknishchay commented on lib/card/theme.module.scss
> +        transition: max-height 1s ease;
- can we have same transition duration for both collapsing and expanding
- test between `linear` and `ease` timing function to check which looks better

2018-12-31 07:33 UTC, kaushiknishchay commented on lib/card/index.js
> +    const Icon = expanded ? FaAngleDoubleUp : FaAngleDoubleDown;
- Use a single icon component and use transform to rotate it, it will ensure the expanding of card body and change of icon is together.

2018-12-31 07:33 UTC, kaushiknishchay commented on lib/card/index.js
> +    const Icon = expanded ? FaAngleDoubleUp : FaAngleDoubleDown;
- Remove little bit of space from bottom of Expand/Collapse icon.
- https://disjfa.github.io/bootstrap-tricks/card-collapse-tricks/ Refer this URL to see the smoothness in card expansion and icon rotation example

2018-12-31 08:59 UTC, kaushiknishchay commented on lib/card/theme.module.scss
> +        transition: max-height 1s ease;
Move `transition` code to common CSS instead of putting in both `expanded` and `collapsed` states

2018-12-31 13:05 UTC, kaushiknishchay submitted a review, later dismissed

2019-01-01 06:44 UTC, KRRISH96 commented on lib/card/index.js
> +      className: classnames(theme['expand-icon'], expanded ? theme.close : theme.open),
```suggestion
      className: classnames(theme['expand-icon'], expanded ? theme.open : theme.close),
```
Expand Button UX feels reverse, Please check screenshot.
When collapsed Arrow points Upwards
![screenshot from 2019-01-01 12-10-55](https://user-images.githubusercontent.com/22497932/50570783-80f50780-0dbe-11e9-977d-74dcf2f3acc7.png)
And downwards when expanded
![screenshot from 2019-01-01 12-11-08](https://user-images.githubusercontent.com/22497932/50570784-85b9bb80-0dbe-11e9-924c-eb13fd2a1ac3.png)

2019-01-01 06:46 UTC, KRRISH96 commented on lib/card/theme.module.scss
> +  font-size: 1.36em;
Add Cursor Pointer.
```suggestion
  font-size: 1.36em;
  cursor: pointer;
```

2019-01-01 06:46 UTC, KRRISH96 requested changes
Only 2 minor changes and good to go.

2019-01-03 07:30 UTC, KRRISH96 approved these changes

2019-01-03 07:32 UTC, merged

2019-01-03 08:17 UTC, rishichawda commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-lite-ui)
- [GitHub release](https://github.com/Codebrahma/react-lite-ui/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: