fix(Checkbox): Fix checkbox design bugs
Codebrahma/react-lite-ui pull request #291
Opened 2018-12-28 13:06 UTC by KRRISH96

### Status :
Ready
##

### Description :
Checkbox design update and bug fix

##
### Related Issues :
#287 

## Todos
- [ ] Tests
- [ ] Documentation

2018-12-30 11:49 UTC, rishichawda requested changes
While hovering on the center portion of the checkbox the cursor is normal and while hovering near the borders it is pointer. Should be pointer anywhere inside the checkbox.

2018-12-31 07:40 UTC, kaushiknishchay requested changes

2018-12-31 07:40 UTC, kaushiknishchay commented on lib/checkbox/theme.module.scss
> +        top: 10%;
- Change to 5% so that check-mark looks more centered

2018-12-31 11:55 UTC, kaushiknishchay approved these changes

2019-01-01 12:54 UTC, rishichawda approved these changes

2019-01-01 12:55 UTC, merged

2019-01-03 08:18 UTC, rishichawda commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-lite-ui)
- [GitHub release](https://github.com/Codebrahma/react-lite-ui/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: