Multiselect design update
Codebrahma/react-lite-ui pull request #296
Opened 2018-12-31 06:32 UTC by rishichawda

### Status :
Ready
##

### Description :

Minor design updates.
Bug fix.

##

### Related Issues :

#287 

## Todos
- [ ] Tests
- [ ] Documentation

2018-12-31 08:28 UTC, kaushiknishchay requested changes
- Change the List Item Hover and selected Values color, Currently both are same.


Selected Values Chip:
- add padding on the left of close icon

2018-12-31 11:28 UTC, rishichawda commented
@kaushiknishchay Updated the hover styles and chip icon. Also added animation on selecting an item.

2018-12-31 12:37 UTC, kaushiknishchay approved these changes

2019-01-01 12:50 UTC, KRRISH96 approved these changes

2019-01-01 12:58 UTC, merged

2019-01-03 08:18 UTC, rishichawda commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-lite-ui)
- [GitHub release](https://github.com/Codebrahma/react-lite-ui/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: